### ISSUE TITLE
Moment of confusion in getting started readme

### ISSUE THREAD

**Issue by andybak** [yourlabs/crudlfap#12]
Where it says "Let's setup the default queryset per user for views and forms etc"

I was confused as to which file this code should be added to. The docs should be explicit here and say something like "Add the following code to your app's urls.py"

**Comment by jpic** [comment]
I made sphinx documentation, which is not finished, lot of documentation is in docstrings, it's blocked because we use ModuleImportError which is new in Py3.6 but RTFD only supports 3.5 I'm sure they'll fix it soonish and it'll help contributing better documentation.

I got a big style update to push too, my current localhost:

![2017-12-16-220147_1501x406_scrot](https://user-images.githubusercontent.com/94636/34074341-0fdd738a-e2ad-11e7-8b85-bb227df3705e.png)

**Comment by jpic** [comment]
For the moment we are running just the test project with the crudlfap dev command. Also, MaterializeCSS is now the UI toolkit in master.

In the next days i will be integrating in another project and will start working on documentation.
